package com.example.springboottest.bean.model;

import java.util.Date;

/**
 * 申请单
 */
public class ApplicationForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_form.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_form.img_name
     *
     * @mbggenerated
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_form.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_form.receipt_number
     *
     * @mbggenerated
     */
    private String receiptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_form.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_form.opedate
     *
     * @mbggenerated
     */
    private Date opedate;

    private String formName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_form.id
     *
     * @return the value of t_application_form.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_form.id
     *
     * @param id the value for t_application_form.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_form.img_name
     *
     * @return the value of t_application_form.img_name
     * @mbggenerated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_form.img_name
     *
     * @param imgName the value for t_application_form.img_name
     * @mbggenerated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_form.img_url
     *
     * @return the value of t_application_form.img_url
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_form.img_url
     *
     * @param imgUrl the value for t_application_form.img_url
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_form.receipt_number
     *
     * @return the value of t_application_form.receipt_number
     * @mbggenerated
     */
    public String getReceiptNumber() {
        return receiptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_form.receipt_number
     *
     * @param receiptNumber the value for t_application_form.receipt_number
     * @mbggenerated
     */
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber == null ? null : receiptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_form.operator
     *
     * @return the value of t_application_form.operator
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_form.operator
     *
     * @param operator the value for t_application_form.operator
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_form.opedate
     *
     * @return the value of t_application_form.opedate
     * @mbggenerated
     */
    public Date getOpedate() {
        return opedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_form.opedate
     *
     * @param opedate the value for t_application_form.opedate
     * @mbggenerated
     */
    public void setOpedate(Date opedate) {
        this.opedate = opedate;
    }

    public String getFormName() {
        return formName;
    }

    public void setFormName(String formName) {
        this.formName = formName;
    }
}