package com.example.springboottest.bean.model;

import java.util.Date;

/**
 * 项目金额
 */
public class Proamount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proamount.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proamount.project_number
     *
     * @mbggenerated
     */
    private String projectNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proamount.amount
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proamount.receipt_number
     *
     * @mbggenerated
     */
    private String receiptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proamount.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proamount.opedate
     *
     * @mbggenerated
     */
    private Date opedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proamount.id
     *
     * @return the value of t_proamount.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proamount.id
     *
     * @param id the value for t_proamount.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proamount.project_number
     *
     * @return the value of t_proamount.project_number
     *
     * @mbggenerated
     */
    public String getProjectNumber() {
        return projectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proamount.project_number
     *
     * @param projectNumber the value for t_proamount.project_number
     *
     * @mbggenerated
     */
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber == null ? null : projectNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proamount.amount
     *
     * @return the value of t_proamount.amount
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proamount.amount
     *
     * @param amount the value for t_proamount.amount
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proamount.receipt_number
     *
     * @return the value of t_proamount.receipt_number
     *
     * @mbggenerated
     */
    public String getReceiptNumber() {
        return receiptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proamount.receipt_number
     *
     * @param receiptNumber the value for t_proamount.receipt_number
     *
     * @mbggenerated
     */
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber == null ? null : receiptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proamount.operator
     *
     * @return the value of t_proamount.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proamount.operator
     *
     * @param operator the value for t_proamount.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proamount.opedate
     *
     * @return the value of t_proamount.opedate
     *
     * @mbggenerated
     */
    public Date getOpedate() {
        return opedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proamount.opedate
     *
     * @param opedate the value for t_proamount.opedate
     *
     * @mbggenerated
     */
    public void setOpedate(Date opedate) {
        this.opedate = opedate;
    }
}