package com.example.springboottest.dao;

import com.example.springboottest.bean.model.Proamount;
import org.apache.ibatis.annotations.Mapper;

/**
 * 申请单表Mapper
 */
@Mapper
public interface ProamountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_proamount
     *
     * @mbggenerated
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_proamount
     *
     * @mbggenerated
     */
    int insert(Proamount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_proamount
     *
     * @mbggenerated
     */
    int insertSelective(Proamount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_proamount
     *
     * @mbggenerated
     */
    Proamount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_proamount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Proamount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_proamount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Proamount record);
}